##spring:
##  datasource:
##    url: jdbc:mysql://localhost:3306/foundandlose
##    username: root
##    password: root
##    driver-class-name: com.mysql.cj.jdbc.Driver
##hbase:
##  config:
##    hbase.zookeeper.quorum:
##    hbase.zookeeper.port:
##    hbase.zookeeper.znode:
##    hbase.client.keyvalue.maxsize:
##    hbase.client.ipc.pool.size:5
server:
  port: 9090
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/fort
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 8888
    connect-timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1

#hbase:
#  config:
#    hbase.zookeeper.quorum: slave1,slave2,slav3
#    hbase.zookeeper.property.clientPort: 2181
#
#

#配置腾讯云的短信
#smsConfig:
#  appId: 1400557427  #腾讯云短信应用id
#  appkey: dbae4fa0a746c533a48a7f67ebf504c7  #腾讯云短信应用key
#  smsSign: 华达州猛学java公众号              #腾讯云短信的签名模板
#  templateId: 1067012
#  invalidTime: 300